Chapter4 課題１
ayako008612/furiphp_exercise pull request #5
Opened 2022-02-23 13:40 UTC by ayako008612

### カリキュラムURL

### 課題番号

課題１

### 現在の状況
chap4-area.php を作成してみたところ、実行できるまで辿り着けません。
return $area = (($top + $bottom) * $height / 2);　この行がどうやらダメのようです。
}### 期待していた動作
return
の後はどのようになるのでしょうか？

### 調べたこと・参考にしたURL

本のP147 を参考

2022-02-24 01:19 UTC, noopy0415 commented
こんにちは✨
現状が把握できていないため確認させてください😊

>chap4-area.php を作成してみたところ、実行できるまで辿り着けません。

実行できる = エラーが出ない ではないので、実行すればエラーなどが表示されると思いますが、エラーもしくは出力結果などを教えてください👍

>return $area = (($top + $bottom) * $height / 2);　この行がどうやらダメのようです。

この行がダメと思ったのはエラーなどを読み取って判断したかと思いますが、どのような内容でしたか?
エラー文なら翻訳してみると答えが書いている場合があります👍

------------------------

以下ざっくりですが、現状のファイルの状態を確認させていただいた結果です。

**chap4_area.php**

calc_area()関数とdisplay_msg()関数の記述している内容が逆になっています😅
- calc_area()関数 => 面積を計算する関数
- display_msg()関数 => メッセージを表示する関数

**chap4_1.php**

内容が課題2の内容を書いているようです😅

確認よろしくおねがいします😊

2022-02-24 23:01 UTC, ayako008612 commented
こんにちは！
①実行しなくても赤い色で表示されているので、エラーと認識することができます。
②return $area = (($top + $bottom) * $height / 2);がエラーだと思ったのは下に２重線があったからです。

2022-02-25 00:41 UTC, noopy0415 commented
こんにちは!
なるほどです😊
エラーだと思ったところまでは良かったのですが、どうして赤くなったのかを調べる方法がわからないと言う認識でよろしいでしょうか?

赤い線が出た状態でマウスカーソルをそこに移動すると以下のようにヒントが表示されると思います。
問題の表示をクリックすると下にエラー文が表示されると思うので、そこを翻訳するなどして読み解くとエラーの原因を調べることができると思います👍
![image](https://user-images.githubusercontent.com/37007364/155631498-694f82f3-986c-424c-b731-88241db83e4c.png)

2022-02-25 11:46 UTC, ayako008612 commented
ヒントが表示されました！
ありがとうございます😄✨

2022-02-26 23:07 UTC, ayako008612 commented
### カリキュラムURL



### 課題番号
chap4 課題1


### 現在の状況

プログラムを実行したときに、Warning: Undefined variable $top in /var/www/html/chap4_1.php on line 4
とエラー表示された。

### 期待していた動作

プログラムを実行したときに面積の値が表示される

### 調べたこと・参考にしたURL

変数を定義していないのに表示しようとしたエラーメッセージ？
参考にしたのは本の P150

2022-02-26 23:42 UTC, kzri4 commented
そのエラーの原因は､エラー文の通りで､変数`$top`に値g

2022-02-26 23:47 UTC, kzri4 commented
そのエラーの原因は､エラー文の通り､変数`$top`に何も代入されていない($top = 10; 等が定義されていない)ということですので､定義するようにお願いします!

2022-02-27 01:26 UTC, ayako008612 commented
変数を定義しましたが、またしてもおなじエラーのようです。

2022-02-27 02:20 UTC, zeeero4 commented on chap4_1.php
> +["上底は？" , "$top" , "cnt" => 10],
追加して頂いた内容は､配列に新しいkeyをvalueが追加されただけで､根本的な解決方法にはなっていないので､配列を使用するのであれば､再度使い方の復習をお願いします🙏

2022-02-27 02:40 UTC, kzri4 commented on chap4_1.php
> +["上底は？" , "$top" , "cnt" => 10],
配列の中に基本､変数は入れないです🙏

2022-03-13 06:12 UTC, ayako008612 commented
### カリキュラムURL
[
](https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise_book/04.md)

### 課題番号

chapter4 課題１

### 現在の状況

「変数を指定し calc_area関数 で面積を求め、戻り値を変数 $area に入れる」の変数の指定の仕方が分かりません。
### 期待していた動作

面積、４５０が＄area に入る

### 調べたこと・参考にしたURL

2022-03-13 08:05 UTC, kazu-taka commented on chap4_1.php
> +}
@ayako008612 
こちらのコードはカリキュラム通り `--------------`の中の部分を修正して下さい✨

```php
$top = 10;
$bottom = 20;
$height = 30;

------------------
関数の結果を$areaに入れる
メッセージ関数の呼び出し
------------------

$top = 40;
$bottom = 50;
$height = 60;

------------------
関数の結果を$areaに入れる
メッセージ関数の呼び出し
------------------
```

## イメージ


```php
$top = 10;
$bottom = 20;
$height = 30;

------------------
$area = 関数実行
メッセージ関数の実行
------------------

$top = 40;
$bottom = 50;
$height = 60;

------------------
関数の結果を$areaに入れる
メッセージ関数の呼び出し
------------------
```

2022-03-15 12:25 UTC, Arisaarisa reviewed
学習お疲れ様です！
落ち着いて本をおさらいしながら自力で解決してみましょう😊

2022-03-15 12:25 UTC, Arisaarisa commented on chap4_price.php
> +    $sum = ($item1 + $item2 + $item3) * 1 / 10;
この辺りの計算式が正しいか確認お願いします！
また、出力に関係するコード (var_dumpなど)はchap4_2phpの方に書くようにしましょう😊

2022-03-15 12:25 UTC, Arisaarisa commented on chap4_price.php
> +function add($item1, $item2,$item3) {;
;が入っています！

2022-03-15 12:25 UTC, Arisaarisa commented on chap4_price.php
> +function total_tax($item1,$item2,$item3) {
引数は$sumになりませんか？！

2022-03-15 12:33 UTC, Arisaarisa commented on chap4_1.php
> +$area = calc_area($top,$bottom,$height);
ここで$areaについて説明していますよね？
なのでchap4_area.phpでおかしなところはありませんか？!
ここが理解できるとうまくいくかと思います😊✨

2022-03-16 12:43 UTC, kazu-taka commented on chap4_1.php
> +?>
@ayako008612 
こちらのセミコロンは不要です✨
最後がPHPのコードを終わる時は、閉じタグ(`?>`)は不要となります☺️
参考
https://thesaibase.com/end-tag/

2022-03-16 12:44 UTC, kazu-taka commented on chap4_2.php
> +require_once __DIR__ . "/chap4_price.php";
@ayako008612 
ファイルの読み込みは、どのファイルを読み込んでいるのかすぐに分かるように、最初に開始タグの直後で行うようにして下さい✨

2022-03-16 12:45 UTC, kazu-taka commented on chap4_2.php
> +<<?php
@ayako008612 
開始タグの`<`が一つ余計です✨

2022-03-16 12:48 UTC, kazu-taka commented on chap4_price.php
> +function display_msg($name,$price,$sum){
@ayako008612 
ここで`$name`をという変数を値を受け取っているので、入力した名前を受け取るべきだと思います✨
しかし、以下のように、関数を呼んでいるところでは、名前が代入されている変数を渡していないので、あやさんが予想している動きになっていないと思われます☺️

```php
display_msg($item1,$item2,$item3,$sum);
```

2022-03-16 19:54 UTC, kazu-taka requested changes
@ayako008612 
コメントしたので修正お願いします☺️

2022-03-16 19:54 UTC, kazu-taka commented on chap4_2.php
> +$sum = add($price,$item1,$item2,$item3);
@ayako008612 
ここの時点で`$price`という変数はまだ定義されていない(何の値も代入していない)ので、渡す事はできません☺️
ですので、`$price`以外の3つの変数を渡して、add関数の中で税込み価格を求めるようにして下さい✨

2022-03-16 19:54 UTC, kazu-taka commented on chap4_2.php
> +display_msg($item1,$item2,$item3,$sum);
@ayako008612 
昨夜私がコメントして部分が修正されていませんでした！
https://github.com/ayako008612/furiphp_exercise/pull/5/files#r827969736


```php
 // 関数を呼んでいる(実行している)場所
display_msg($item1,$item2,$item3,$sum);

// 実行されている関数
function display_msg($name,$price,$sum){ 
    $msg = <<<EOM
$name 様
ご注文承りました。
合計 $price 円です。
$sum 円（税込）になります。\n
EOM;
    echo $msg;
}
```

渡している変数が`$item1,$item2,$item3,$sum`であるにも関わらず、受け取っている変数が`$name,$price,$sum`となっています。
渡している変数が4つで、受け取っている変数が3つなので、数が合っていません。
また、一番最初に渡している変数が`$item1`であるにも関わらず、受け取る際に`$name`としているので、`$name`には名前ではないものがセットされています。
本来渡すべきものを渡すように修正して下さい✨

2022-03-17 04:52 UTC, kazu-taka requested changes
@ayako008612 
コメントしたので修正お願いします☺️

2022-03-17 04:52 UTC, kazu-taka commented on chap4_price.php
> +    $sum = ($item1 + $item2 + $item3) + (($item1 + $item2 + $item3) * 0.1);
@ayako008612
税込み価格を求める際は、全ての価格 * 1.1にした方が計算が短くなるので、修正お願いします✨

2022-03-17 04:52 UTC, kazu-taka commented on chap4_2.php
> +display_msg($name,$item1,$item2,$item3);
@ayako008612 
処理の流れは以下の通りとなります☺️

- 氏名と金額を入力
- total_tax関数で税込み金額を求める
- display_msg関数でメッセージを出力

```php
$sum = add($item1,$item2,$item3);
display_msg($name,$item1,$item2,$item3);
```

上記の2行がありますが、$sumを求めているがどこでも使用していないので不要となります。
また、display_msg関数はtotal_tax関数の後に実行するべきなので、最初のdisplay_msg関数は不要です！

2022-03-17 04:52 UTC, kazu-taka commented on chap4_2.php
> +display_msg($name,$item1,$item2,$item3);
@ayako008612 
total_tax関数で求めた税込み価格の$priceを使用してないので、display_msgに渡して下さい✨
display_msg関数の中で必要な変数のみ渡すようにして下さい☺️

2022-03-18 08:32 UTC, narusesuzuki commented
> カリキュラムURL 課題番号 chapter4 課題２
> 
> 現在の状況 山田様が何故２回繰り返して表示されるのでしょうか？
> 
> 期待していた動作 調べたこと・参考にしたU <img alt="スクリーンショット 2022-03-17 20 39 08" width="752" src="https://user-images.githubusercontent.com/92987860/158802126-3e926d4a-77a1-4c46-9de7-a5dc743f91f9.png"> RL

@ayako008612
こんにちは！😊  
以前一真さんがコメントしていた以下の内容がヒントです！([コメントのリンク](https://github.com/ayako008612/furiphp_exercise/pull/5#discussion_r828752406))

> また、display_msg関数はtotal_tax関数の後に実行するべきなので、最初のdisplay_msg関数は不要です！

<br>

不要なdisplay_msg関数を実行しないように、修正してみてください😊🙏

2022-03-18 21:41 UTC, kazu-taka commented on chap4_pet.php
> +count($animal);
@ayako008612 
エラーメッセージをコピーして、こちらに貼り付けて頂いてもよろしいでしょうか？☺️
また、そのエラーメッセージを見て、あやさん何にどう解釈したか教えて下さい✨

2022-03-18 22:18 UTC, ayako008612 commented on chap4_pet.php
> +count($animal);
<img width="726" alt="スクリーンショット 2022-03-19 7 03 41" src="https://user-images.githubusercontent.com/92987860/159091195-9e197d24-5e71-4d6e-80cd-9432e4f49c59.png">
１、$animal = array($owners);　　がダメ

２、$animal_types(array_unique($owners));　　がダメ

array_unique関数がよく分りませんでした。

array_unique(array $array, int $flags = SORT_STRING): array

2022-03-18 22:36 UTC, kazu-taka commented on chap4_pet.php
> +count($animal);
@ayako008612 
エラーメッセージは翻訳してみて下さい✨
$ownersと$animal_typesが未定義(値を代入している場所がないのに、参照しようとしている)となってます☺️
<img width="705" alt="image" src="https://user-images.githubusercontent.com/5278718/159092788-82007ddc-b561-4875-944d-a597b9bf1e4d.png">


以下のコードが関数の外(display_msgの外)で実行されているので、display_msg内からは$animalや$animal_typesを参照することができません^^;
関数内で以下の処理を実行して、それぞれの変数を求めてから、文字列として出力するようにして下さい✨
```php
$animal = array($owners);
$animal_types(array_unique($owners));

$animal = $animal_types;
$animal = implode(',',$animal);

$animal = array($owners);
count($animal);
```

2022-03-19 23:23 UTC, kazu-taka commented on chap4_pet.php
> +$count 匹飼っています。
@ayako008612 
プログラムは上から下に向かって実行されるので、$name、$animal、$countを先に求めてから、使用する(参照する)ように修正お願いします✨

2022-03-20 00:44 UTC, kazu-taka commented on chap4_pet.php
> +}
@ayako008612 
array_uniqueやimplodeやcountはPHPの標準関数で存在するので、自作しなくても良いです☺️
以下のような処理になるように修正お願いします！

```php
function display_msg($name,$animal,$count){ 
    // $animalを求める

    // $countを求める

    $msg = <<<EOM
$name さんは
$animal を
$count 匹飼っています。\n
EOM;
function display_msg($owner){
    $name = ($owner);
    return $name;
}
```

2022-03-20 02:15 UTC, kazu-taka commented on chap4_pet.php
> +}
@ayako008612 
>array_uniqueやimplodeやcountはPHPの標準関数で存在するので、自作しなくても良いです☺️
ここの部分はうまく伝わってないですかね！？
自作しなくても良い=`function array_unique`等は不要ということになります☺️
`chap4_3.php`から`display_msg`関数を実行しているので、`display_msg`関数の中身が空っぽだと何も処理が実行されません。
私が先程書いたコードがほぼ答えになります！
https://github.com/ayako008612/furiphp_exercise/pull/5#discussion_r830543101

<br>

今回は解答を公開するので、解答を見ても分からない部分を整理して、質問お願いします:bow:

`chap4_pet.php`
```php
<?php
function display_msg($owner)
{
    // animal配列要素で重複しているものを削除して$animal_typesに代入する
    $animal_types = array_unique($owner["animal"]);
    // 重複している要素を削除し変数にした$animal_typesを文字列で連結し、$animalに代入
    $animal  = implode("、", $animal_types);
    // 配列の中のanimal配列の数をカウントする
    $count = count($owner["animal"]);

    $msg = <<<EOM
{$owner["name"]}さんは
{$animal}を
{$count}匹飼っています。\n
EOM;
    echo $msg;
}
```

2022-03-20 06:17 UTC, ayako008612 commented
課題３まで全て完了しました！
確認お願いします✨

2022-03-20 07:18 UTC, merged